version: '3'
services:
  data-file-collector:
    image: nexus3.onap.org:10001/onap/org.onap.dcaegen2.collectors.datafile.datafile-app-server
    command: >
      --dmaap.dmaapConsumerConfiguration.dmaapHostName=<HOST-TO-SET-DMAAP-MR>
      --dmaap.dmaapConsumerConfiguration.dmaapPortNumber=3904
      --dmaap.dmaapConsumerConfiguration.dmaapTopicName=/events/unauthenticated.VES_NOTIFICATION_OUTPUT
      --dmaap.dmaapConsumerConfiguration.dmaapProtocol=http
      --dmaap.dmaapConsumerConfiguration.dmaapUserName=admin
      --dmaap.dmaapConsumerConfiguration.dmaapUserPassword=admin
      --dmaap.dmaapConsumerConfiguration.dmaapContentType=application/json
      --dmaap.dmaapConsumerConfiguration.consumerId=C12
      --dmaap.dmaapConsumerConfiguration.consumerGroup=OpenDCAE-c12
      --dmaap.dmaapConsumerConfiguration.timeoutMs=-1
      --dmaap.dmaapConsumerConfiguration.message-limit=-1
      --dmaap.dmaapBusControllerConfiguration.dmaapHostName=<HOST-TO-SET-DMAAP-DR>
      --dmaap.dmaapBusControllerConfiguration.dmaapPortNumber=8443
      --dmaap.dmaapBusControllerConfiguration.dmaapTopicName=publish
      --dmaap.dmaapBusControllerConfiguration.dmaapDrFeedName=bulk_pm_feed
      --dmaap.dmaapBusControllerConfiguration.dmaapProtocol=https
      --dmaap.dmaapBusControllerConfiguration.dmaapUserName=dradmin
      --dmaap.dmaapBusControllerConfiguration.dmaapUserPassword=dradmin
      --dmaap.dmaapBusControllerConfiguration.dmaapContentType=application/octet-stream
      --dmaap.ftpesConfig.keyCert=config/ftpKey.jks
      --dmaap.ftpesConfig.keyPassword=secret
      --dmaap.ftpesConfig.trustedCA=config/cacerts
      --dmaap.ftpesConfig.trustedCAPassword=secret
    entrypoint:
    - java
    - -Dspring.profiles.active=dev
    - -jar
    - /target/datafile-app-server.jar
    ports:
    - "8100:8100"
    - "8433:8433"
    restart: always

